### ISSUE TITLE
Armor Template Class is Frozen

### ISSUE THREAD

**Issue by Destarianon** [Sindusk/armoury#1]
Having a crash during load, unsure what could be causing this.

Log Snippet Below:
[10:26:02 PM] INFO mod.sin.armoury.CombatsTweaks: Instrument: CombatHandler - getSpeed call to max successful. [Reason: Adjust swing timer.]
[10:26:02 PM] INFO mod.sin.armoury.CombatsTweaks: Instrument: CombatHandler - getSpeed call to max successful. [Reason: Adjust swing timer.]
[10:26:02 PM] INFO mod.sin.armoury.CombatsTweaks: Instrument: Creature - deductFromWeaponUsed call to put successful. [Reason: Fix saved swing timer.]
[10:26:02 PM] INFO mod.sin.armoury.ShieldsTweaks: Instrument: CombatHandler - checkShield call to setDamage successful. [Reason: Enable shield damage enchants.]
[10:26:02 PM] INFO mod.sin.armoury.ShieldsTweaks: Insert: CombatHandler - checkShield successful. [Reason: Enable shield speed enchants.]
[10:26:02 PM] INFO mod.sin.armoury.WeaponsTweaks: Set Body: Weapon - getMaterialDamageBonus successful. [Reason: Enable weapon material damage modifications.]
[10:26:02 PM] INFO mod.sin.armoury.WeaponsTweaks: Set Body: Weapon - getBaseSpeedForWeapon successful. [Reason: Enable weapon material speed modifications.]
[10:26:02 PM] INFO mod.sin.armoury.WeaponsTweaks: Set Body: Weapon - getMaterialParryBonus successful. [Reason: Enable weapon material parry modifications.]
[10:26:02 PM] INFO mod.sin.armoury.WeaponsTweaks: Set Body: Weapon - getMaterialArmourDamageBonus successful. [Reason: Enable weapon material armour damage modifications.]
[10:26:02 PM] SEVERE org.gotti.wurmunlimited.serverlauncher.DelegatedLauncher: com.wurmonline.server.combat.ArmourTemplate class is frozen
java.lang.RuntimeException: com.wurmonline.server.combat.ArmourTemplate class is frozen
	at javassist.CtClassType.checkModify(CtClassType.java:321)
	at javassist.CtBehavior.setBody(CtBehavior.java:460)
	at javassist.CtBehavior.setBody(CtBehavior.java:440)
	at mod.sin.lib.Util.setBodyDeclared(Util.java:158)
	at mod.sin.armoury.MaterialsTweaks.preInit(MaterialsTweaks.java:447)
	at mod.sin.armoury.ArmouryModMain.preInit(ArmouryModMain.java:393)
	at org.gotti.wurmunlimited.modloader.ModLoaderShared.lambda$loadModsFromModDir$6(ModLoaderShared.java:166)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.gotti.wurmunlimited.modloader.ModLoaderShared.loadModsFromModDir(ModLoaderShared.java:164)
	at org.gotti.wurmunlimited.serverlauncher.DelegatedLauncher.main(DelegatedLauncher.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javassist.Loader.run(Loader.java:286)
	at org.gotti.wurmunlimited.serverlauncher.ServerLauncher.main(ServerLauncher.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at PatchedLauncher.main(PatchedLauncher.java:20)

**Comment by Destarianon** [comment]
Dug into the repo and I can see a "fix freezing error" commit.
To clarify, I am using the newest versions of both armoury and library. Still getting the issue.

**Comment by Sindusk** [comment]
I would need a full log in order to assist at all. I wont be able to fix the issue directly (I'm no longer coding anything in Wurm), but I'll be able to tell you what's causing it.

**Comment by Destarianon** [comment]
Sorry for the delay on that. Here is a log file. I have a pretty large load order, so if I need to spin up a server running the bare minimum mods, I can do that.
[server.log](https://github.com/Sindusk/armoury/files/4976054/server.log)
